// <auto-generated />
using System;
using DistributedGitStorage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DistributedGitStorage.Data.Migrations
{
    [DbContext(typeof(DistributedGitStorageDbContext))]
    partial class DistributedGitStorageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DistributedGitStorage.Data.Models.ReplicationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Generation")
                        .HasColumnType("bigint");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceNode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TargetNode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.HasIndex("RepositoryId", "TargetNode", "Generation")
                        .IsUnique();

                    b.ToTable("replication_jobs", (string)null);
                });

            modelBuilder.Entity("DistributedGitStorage.Data.Models.RepositoryPlacement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CurrentGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StorageClusterId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_repository_placements_name");

                    b.HasIndex("StorageClusterId");

                    b.ToTable("repository_placements", (string)null);
                });

            modelBuilder.Entity("DistributedGitStorage.Data.Models.RepositoryReplica", b =>
                {
                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageNode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("AppliedGeneration")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LastSuccessfulReplicationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefsHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("RepositoryId", "StorageNode");

                    b.HasIndex("RepositoryId", "Status", "AppliedGeneration");

                    b.ToTable("repository_replicas", (string)null);
                });

            modelBuilder.Entity("DistributedGitStorage.Data.Models.StorageCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("storage_clusters", (string)null);
                });

            modelBuilder.Entity("DistributedGitStorage.Data.Models.StorageNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InternalAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StorageClusterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StorageClusterId");

                    b.ToTable("storage_nodes", (string)null);
                });

            modelBuilder.Entity("DistributedGitStorage.Data.Models.ReplicationJob", b =>
                {
                    b.HasOne("DistributedGitStorage.Data.Models.RepositoryPlacement", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DistributedGitStorage.Data.Models.RepositoryPlacement", b =>
                {
                    b.HasOne("DistributedGitStorage.Data.Models.StorageCluster", "StorageCluster")
                        .WithMany("RepositoryPlacements")
                        .HasForeignKey("StorageClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StorageCluster");
                });

            modelBuilder.Entity("DistributedGitStorage.Data.Models.RepositoryReplica", b =>
                {
                    b.HasOne("DistributedGitStorage.Data.Models.RepositoryPlacement", "Repository")
                        .WithMany("Replicas")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DistributedGitStorage.Data.Models.StorageNode", b =>
                {
                    b.HasOne("DistributedGitStorage.Data.Models.StorageCluster", "StorageCluster")
                        .WithMany("Nodes")
                        .HasForeignKey("StorageClusterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StorageCluster");
                });

            modelBuilder.Entity("DistributedGitStorage.Data.Models.RepositoryPlacement", b =>
                {
                    b.Navigation("Replicas");
                });

            modelBuilder.Entity("DistributedGitStorage.Data.Models.StorageCluster", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("RepositoryPlacements");
                });
#pragma warning restore 612, 618
        }
    }
}
