<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
</PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GitalyControlPlane.Data\GitalyControlPlane.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.31.1" />
    <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.72.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.18" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.18" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\vendor\gitaly\proto\lint.proto" GrpcServices="None" ProtoRoot="..\..\vendor\gitaly\proto" />
    <Protobuf Include="..\..\vendor\gitaly\proto\errors.proto" GrpcServices="None" ProtoRoot="..\..\vendor\gitaly\proto" />
    <Protobuf Include="..\..\vendor\gitaly\proto\shared.proto" GrpcServices="None" ProtoRoot="..\..\vendor\gitaly\proto" />
    <Protobuf Include="..\..\vendor\gitaly\proto\repository.proto" GrpcServices="Client" ProtoRoot="..\..\vendor\gitaly\proto" />
    <Protobuf Include="..\..\vendor\gitaly\proto\packfile.proto" GrpcServices="None" ProtoRoot="..\..\vendor\gitaly\proto" />
    <Protobuf Include="..\..\vendor\gitaly\proto\smarthttp.proto" GrpcServices="Client" ProtoRoot="..\..\vendor\gitaly\proto" />
  </ItemGroup>

</Project>
