apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: storage-node
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: storage-node
      app.kubernetes.io/part-of: distributed-git-storage
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: control-plane
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: control-plane
      app.kubernetes.io/part-of: distributed-git-storage
